name: frontend
description: "Dissertation 2024-2025"
publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cache:
    path: packages/cache
  cupertino_icons: ^1.0.6
  bloc: ^9.0.0
  camera: ^0.11.0+2
  equatable: ^2.0.5
  flutter_bloc: ^9.0.0
  firebase_core: ^3.6.0
  firebase_analytics: ^11.3.3
  go_router: ^14.6.2
  firebase_auth: ^5.3.4
  logger: ^2.5.0
  alert_banner: ^1.0.1
  dio: ^5.7.0
  get_it: ^8.0.3
  carousel_slider: ^5.0.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.2.2
  model_viewer_plus: ^1.9.1
  flutter_3d_controller: ^2.1.0
  hydrated_bloc: ^10.0.0
  dart_mappable: ^4.4.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dart_mappable_builder: ^4.4.0
  build_runner: ^2.4.15
  mockito: ^5.4.5


flutter:
  uses-material-design: true

  assets:
    - assets/test_object.glb
